spring.application.name=comparar

# Configuración de tamaño máximo de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuración del puerto (para Google Cloud Run usar 8080)
server.port=8081
